language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - main

jobs:
   include:
     - stage: Produce Coverage
       script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
