# Adapted coveralls_simple
# https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands
version: 2.1

orbs:
    coveralls: coveralls/coveralls@1.0.6

jobs:
    build:
        docker:
            - image: 'cimg/node:16.13.2'
        steps:
            - checkout
            - run:
                  name: Install and Test
                  command: npm install && npx jest --coverage
            - coveralls/upload:
                  token: COVERALLS_REPO_TOKEN
                  verbose: true
